services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/target
      # Below is required for Hot Reload
      - ~/.m2:/root/.m2 # Cache Maven dependencies
      - ./backend/src:/app/src # Mount the source code
      - ./backend/target:/app/target # Mount the target directory
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=system_integration
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
      - DB_ROOT_PASSWORD=my-secret-pw
    command: mvn spring-boot:run
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: db-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: system_integration
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      # - "3306:3306"
      - "3307:3306" # Map local port 3307 to container port 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-data:
