version: "3.8"

services:
  mysql:
    image: mysql:latest # Or use arm64v8/mysql:latest for Raspberry Pi
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PASSWORD: my-secret-pw
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
