# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: myusername/my-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PASSWORD
              value: "my-secret-pw"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 3000
  selector:
    app: backend
