apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - mvn
            - spring-boot:run
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PASSWORD
              value: my-secret-pw
          image: backend
          name: backend
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: backend-cm0
            - mountPath: /app/target
              name: backend-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: backend-cm0
          name: backend-cm0
        - name: backend-claim1
          persistentVolumeClaim:
            claimName: backend-claim1
